name: proc_tweet

on:
  schedule:
    - cron: '5 4,8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  proc_tweet:
    runs-on: ubuntu-20.04
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install remotes
        run: Rscript -e 'install.packages("remotes", dependencies = TRUE)'
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install proceduralnames
        run: Rscript -e 'remotes::install_github("mikemahoney218/proceduralnames")'
      - name: Create and post tweet
        run: Rscript proc_tweet.R
