name: proc_tweet

on:
  schedule:
    - cron: '5 */4 * * *'
  workflow_dispatch:

jobs:
  proc_tweet:
    runs-on: ubuntu-20.04
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install system dependencies
        run: |
          sudo apt install -y libcurl4-openssl-dev libgit2-dev libssh2-1-dev
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - name: Install packages
        run: Rscript -e 'lapply(c("remotes", "rtweet"), install.packages); remotes::install_github("mikemahoney218/proceduralnames"); remotes::install_github("mikemahoney218/gemm")'
      - name: Create and post tweet
        run: Rscript proc_tweet.R
